### ISSUE TITLE
How can I help

### ISSUE THREAD

**Issue by posix4e** [jetlang/rust#1]
I loved the jetlang library in java. I'm currently working on eventual. Shall we join forces?

**Comment by mrettig** [comment]
Alex,

What did you have in mind? I'd be interested in making a high performance
messaging library in rust.  Channels are fine messaging option for the core
library, but for large applications I want something with better
performance and more features (e.g. message broadcast).

Mike

**Comment by posix4e** [comment]
I'm already working on eventual. There's also gj which has a slightly
different take on it. We all have a slightly different view how it should
work which is cool. Perhaps we should all chat on irc #raft on mozilla's
irc.

On Fri, Aug 28, 2015 at 1:54 PM mrettig notifications@github.com wrote:

> Alex,
> 
> What did you have in mind? I'd be interested in making a high performance
> messaging library in rust. Channels are fine messaging option for the core
> library, but for large applications I want something with better
> performance and more features (e.g. message broadcast).
> 
> Mike
> 
> On Fri, Aug 28, 2015 at 12:44 PM, Alex Newman notifications@github.com
> wrote:
> 
> > I loved the jetlang library in java. I'm currently working on eventual.
> > Shall we join forces?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jetlang/rust/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jetlang/rust/issues/1#issuecomment-135885609.
> 
> ## 

Sent from my mobile 5045076749
Alex Newman

**Comment by mrettig** [comment]
My approach would be complementary to gj/eventual. In my domain, I don't
use promises or futures. The applications I write are stateful and low
latency.  A pure messaging solution works well without ever needing a
promise or future. I think the solutions can be developed independently and
used together if needed.

If you do chat on irc, let me know the time and I'll probably drop in to
lend my 2 cents.

Thanks,

Mike

**Comment by posix4e** [comment]
I am there now. Come bug me somewhere on mozilla's irc

On Mon, Aug 31, 2015 at 2:56 PM mrettig notifications@github.com wrote:

> My approach would be complementary to gj/eventual. In my domain, I don't
> use promises or futures. The applications I write are stateful and low
> latency. A pure messaging solution works well without ever needing a
> promise or future. I think the solutions can be developed independently and
> used together if needed.
> 
> If you do chat on irc, let me know the time and I'll probably drop in to
> lend my 2 cents.
> 
> Thanks,
> 
> Mike
> 
> On Fri, Aug 28, 2015 at 3:58 PM, Alex Newman notifications@github.com
> wrote:
> 
> > I'm already working on eventual. There's also gj which has a slightly
> > different take on it. We all have a slightly different view how it should
> > work which is cool. Perhaps we should all chat on irc #raft on mozilla's
> > irc.
> > 
> > On Fri, Aug 28, 2015 at 1:54 PM mrettig notifications@github.com
> > wrote:
> > 
> > > Alex,
> > > 
> > > What did you have in mind? I'd be interested in making a high
> > > performance
> > > messaging library in rust. Channels are fine messaging option for the
> > > core
> > > library, but for large applications I want something with better
> > > performance and more features (e.g. message broadcast).
> > > 
> > > Mike
> > > 
> > > On Fri, Aug 28, 2015 at 12:44 PM, Alex Newman <
> > > notifications@github.com>
> > > wrote:
> > > 
> > > > I loved the jetlang library in java. I'm currently working on
> > > > eventual.
> > > > Shall we join forces?
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/jetlang/rust/issues/1.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/jetlang/rust/issues/1#issuecomment-135885609.
> > > 
> > > ## 
> > 
> > Sent from my mobile 5045076749
> > Alex Newman
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jetlang/rust/issues/1#issuecomment-135886414.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jetlang/rust/issues/1#issuecomment-136512271.
> 
> ## 

Sent from my mobile 5045076749
Alex Newman

**Comment by posix4e** [comment]
I think we are on opposite time zones. I can tell you I am a huge lover of jetlang on java, but I often used them in combination with futures or channels. I agree that it's complimentary, nonetheless I'd love to make the choices for users clearer than they already are. Also i'd love to help

**Comment by mrettig** [comment]
The jetlang rust implementation was just a spike to get to know rust. It
only adds a thin layer on top of rust channels. I'll let you know if I get
serious about writing something crate worthy.

Mike
